FROM alpine:latest

# Renaming to demonstrate flow tracking
ENV RENAMED_INPUT_TEXT="${input_text}"
ENV RENAMED_USER_INPUT_VAR="${user_input_var}"


CMD echo "${RENAMED_INPUT_TEXT}" && echo "${RENAMED_USER_INPUT_VAR}"
